---
name: Issue
about: Submit an issue to the repository
title: Remember to Capitalize
labels: ''
assignees: 'sam-mata'
---

Blurb about the issue

#### Checklist:
- [ ] todo
- [ ] todo
- [ ] todo

#### Related Issues:
- #1

#### Additional Information:
1. link to resource
