name: Update Requirements

on:
    push:
        branches:
            - main

jobs:
    update-requirements:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install pipreqs
              run: |
                  python -m pip install --upgrade pip
                  pip install pipreqs

            - name: Update requirements.txt
              run: |
                  pipreqs --force

            - name: Generate library documentation table
              run: |
                  python <<EOF
                  # ... (Python script remains the same)
                  EOF

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.ACCESS_TOKEN }}
                  branch: update-requirements
                  title: Update requirements.txt and LIBRARIES.md
                  body: |
                      This pull request updates the `requirements.txt` and `LIBRARIES.md` files.
                      - `requirements.txt` has been updated with the latest package versions.
                      - `LIBRARIES.md` has been generated with the updated library information.
                  commit-message: Update requirements.txt and LIBRARIES.md
                  delete-branch: true
