name: Update Requirements

on:
  push:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pipreqs
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs

    - name: Update requirements.txt
      run: |
        pipreqs --force

    - name: Generate library documentation table
      run: |
        python <<EOF
        # ... (Python script remains the same)
        EOF

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add requirements.txt LIBRARIES.md
        git commit -m "Update requirements.txt and LIBRARIES.md" || echo "No changes to requirements.txt or LIBRARIES.md"

    - name: Push changes
      run: |
        git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main